### ISSUE TITLE
Trying to execute hicBuildMatrix but have error with biopython

### ISSUE THREAD

**Issue by JayVaz18** [deeptools/HiCExplorer#609] opened 2020-09-29 13:21 UTC
Hey guys, 

I'm interested in using hicexplorer but when I run the hicBuildMatrix command (from the tutorial) I get the following error:

**Traceback (most recent call last):
  File "/Users/jvazqu09/anaconda3/bin/hicBuildMatrix", line 4, in <module>
    from hicexplorer.hicBuildMatrix import main
  File "/Users/jvazqu09/anaconda3/lib/python3.6/site-packages/hicexplorer/hicBuildMatrix.py", line 27, in <module>
    from Bio.Alphabet import generic_dna
  File "/Users/jvazqu09/anaconda3/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.**

Do you know why this is and how I can possibly go about fixing it?

Thanks.

**Comment by joachimwolff** [comment] 2020-10-05 18:02
Hi,

this is caused by a dependency of us. Biopython decided to remove the specific part in their source code without much announcement and in a minor version. 
Please downgrade your biopython to 1.76
`conda install biopython==1.76` in your specific environment should fix the issue for the momement. We work on a 3.5.2 version of HiCExplorer fixing this issue too.

**Comment by bgruening** [comment] 2020-10-05 20:21
Maybe that helps: https://biopython.org/wiki/Alphabet

**Comment by joachimwolff** [comment] 2020-10-06 14:41
Should be fixed with release 3.5.2. Please reopen if the issue still exists in this release.

**Closed by joachimwolff** 2020-10-06 14:41 UTC
