### ISSUE TITLE
raw values used when cool file as input

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCExplorer#255] opened 2018-05-22 15:05 UTC
Hello,
I generated a matrix from another pipeline using cooler and used cooler to normalize it. When I use this matrix as input in hicplotmatrix or hicplottad in hicexplorer.usegalaxy.eu, it is only the raw values which are used. How could I use the normalized values (using the weights encoded in the cool file)?
Many thanks,
Lucille

**Comment by joachimwolff** [comment] 2018-05-22 15:29
Dear Lucille,

we apply the correction factors on the data as long as they are stored in the 'weight' column. Therefore I am a bit surprised why it is not working for you. I can offer you two things:
1. You can send me the concerning matrix and I will check it on my own what goes wrong.
2. In the meantime you can use the matrix as input with our tool 'hicCorrectMatrix' and correct the data again. If you don't have enough computing resources we provide a webserver for you: hicexplorer.usegalaxy.eu.

Please check the version of HiCExplorer, the up to date one is 2.1.3 and we apply the correction factors since version 2.1.

I hope I could help and don't hesitate to ask more questions.

Best,

Joachim

**Comment by lldelisle** [comment] 2018-05-22 15:48
I used the webserver so I guessed it is up to date. How can I provide you the cool file in a "private way" or could you impersonate my account on the webserver (lucille.delisle@epfl.ch)?

Thanks,

Lucille

**Comment by joachimwolff** [comment] 2018-05-22 16:56
Thanks for sharing the data. 

I can confirm that the correction factors are applied in a correct way. If they are not applied the range of the values is in the hunderts, not in the millions; which is really high and I am not sure if this should be that way. 

What has let to your assumption that the correction factors were not applied? Maybe this helps to figure out what is wrong. 

Ping @fidelram Do you know if the data is good if the uncorrected data is in the range of 0 - 500 but the correct one is 0 - 8,000,000?

**Comment by lldelisle** [comment] 2018-05-23 07:08
In fact the weights are applied the contrary way I was expecting. I was expecting values very low as the sum of each line/column should be 1. So the picture was really different from expected.

**Comment by lldelisle** [comment] 2018-05-23 07:27
I added to the shared history the matrices I was expecting to plot.

**Comment by joachimwolff** [comment] 2018-05-23 09:07
We have a bug concerning the correction factors and cooler files. I have to investigate if it only happens if the values should be in the rang of 0 to 1 or if it is a general issue. To have non-normalized values in the hundreds and to have normalized ones in the millions is ridiculous.

**Comment by joachimwolff** [comment] 2018-05-25 09:07
I had to think about your normalization that the sum of each line/column should sum up to one. I would not recommend doing so of the following reasons:
1. You work with a contact matrix. It is not logical to have signed integers as a contact and this is quite likely to appear if a line/column should sum up to 1. Valid value range of a contact matrix is [0 to +inf].
2. By doing the normalization in this way I think important properties of a contact matrix are destroyed. The relations between the values is no longer kept and the resulting contact matrix is giving you wrong results. Lets assume the following: A contact matrix which has only values at the diagonal, normalizing that every row/column summs up to 1 will replace all values on the diagonal with 1. 

I will fix the normalization bug and I can recommend to not do the normalization of the contact matrix in this way.

**Comment by lldelisle** [comment] 2018-05-25 09:41
In hicexplorer.usegalaxy.eu, there is a tool: hicCorrectMatrix run Imakaev's iterative correction over a Hi-C contact matrix. I guess it does the normalization so that the sum of every row and column is the same (maybe not 1 but any other value). I thinkd that the iteractive correction helps to see the TADs...
Maybe I was not clear, I generated a contact map with positive integer values, then I applied to correction with cooler (cooler balance which does to ice correction (Imakaev)). The output is a cooler file with the weights adjusted so the sum of each row is more or less one (values between 0 and 1).
That is true that the properties of the contact matrix are distroyed but for example if you have a bin where half of the sequence is difficult to map, I want to normalize to have the sum of this line close to the neighbours...

**Comment by joachimwolff** [comment] 2018-05-25 10:17
Correction of the data needs to be done, I agree with you. I am just a bit surprised by the method cooler is using, therefore I will get in contact with them, check the literature and come back to you to solve this issue. 
In the meantime I will provide a new version of HiCExplorer with an option to a) apply the correction in a way cooler wants to have it, b) is having the option to run the correction on the raw data of a cooler file with our correction function (which I am trusting a bit more in the moment, but maybe I am wrong on that, let's see.)

**Comment by joachimwolff** [comment] 2018-05-25 14:17
I changed the behavior a bit in the branch 'cooler_correction_patch'. See my longer comment in #254.

I hope you can work with the terminal based version, to change it on the webserver I have to merge this branch to master and for this I need to do more testing. I hope to achieve this within the next 3 weeks.

**Comment by joachimwolff** [comment] 2018-12-04 11:09
Issue should be fixed with release 2.2.

**Closed by joachimwolff** 2018-12-04 11:09 UTC
