### ISSUE TITLE
error in file order

### ISSUE THREAD

**Issue by jiangshan529** [deeptools/HiCExplorer#703] opened 2021-04-09 03:06 UTC
Hi, I have two questions.
1. When I try to use hicbuildmatrix,  it shows the error "Be sure that the sam files have the same read order If using Bowtie2 or Hisat2 add the --reorder option". However, I used bwa to do the mapping and the first few rows of the two sam files seem to be in the same order. How to deal with this?
2. I want to plot the arcs plot of the regions having interactions, how should I get the bed/arcs file for this when using pyGenomeTracks ?

**Comment by LeilyR** [comment] 2021-04-09 07:10
could you please try to sort your bam files by read names using `samtools sort -n`.

**Comment by jiangshan529** [comment] 2021-04-09 09:06
Hi, it reports the same error.

LeilyR ***@***.***> 于2021年4月9日周五 下午3:10写道：

**Comment by LeilyR** [comment] 2021-04-09 09:33
Can you provide us with a bit more info. about the version you use, the mapping command and hicBuildMatrix command line?

**Comment by jiangshan529** [comment] 2021-04-09 11:51
Hi, the bwa version is 0.7.5a, hicexplorer version is 3.6.
mapping command is: bwa mem -A1 -B4 -E50 -L0 hg19.fa A.fq 2>>A.log|samtools
view -Shb - > A1.bam;
hicbuildmatrix command is : hicBuildMatrix -s A1.sam A2.sam -rs
mboI_restriction_site_positions.bed --danglingSequence GATC -o
chr17_1mb.cool --region chr17:0-80000000 --binSize 1000000
--restrictionSequence GATC --QCfolder QC_20_5kb.
the full error information is :
INFO:hicexplorer.hicBuildMatrix:dangling sequences to check are {'GATC':
{'pat_forw': 'GATC', 'pat_rev': 'GATC'}}

Traceback (most recent call last):
  File "/biosoft/yes/envs/hicexplorer36/bin/hicBuildMatrix", line 7, in
<module>
    main()
  File
"/biosoft/yes/envs/hicexplorer36/lib/python3.8/site-packages/hicexplorer/hicBuildMatrix.py",
line 1290, in main
    one_mate_low_quality_, iter_num_ = readBamFiles(pFileOneIterator=str1,
  File
"/biosoft/yes/envs/hicexplorer36/lib/python3.8/site-packages/hicexplorer/hicBuildMatrix.py",
line 710, in readBamFiles
    assert mate1.qname == mate2.qname, "FATAL ERROR {} {} " \
AssertionError: FATAL ERROR A00877:597:HVV2LDSXY:2:1101:1217:21887
A00877:597:HVV2LDSXY:2:1101:1217:22326 Be sure that the sam files have the
same read order If using Bowtie2 or Hisat2 add the --reorder option

LeilyR ***@***.***> 于2021年4月9日周五 下午5:33写道：

**Comment by LeilyR** [comment] 2021-04-09 13:12
I assume it is typo that you generated A1.bam and use A1.sam right? just in case you missed it. 
Also you have said that you tried samtools sort -n A1.bam and samtools sort -n A12.bam and still got the same error? 
If all these failed you can try to compare your read ids from both bam files. and see if there is anything wrong there. The error shows the 2 id which are not matching. (you can use samtools view and cut -f1 to get the list of read ids)

**Comment by jiangshan529** [comment] 2021-04-09 13:53
Thanks. I tried both the sam files and bam files, and sorted A1 and A2
files, it still shows the error.
There are millions of reads in each bam file, is there an easy way to see
if they are in the same order?
Thanks

LeilyR ***@***.***> 于2021年4月9日周五 下午9:12写道：

**Comment by jiangshan529** [comment] 2021-04-09 13:56
They are in the same order, but there are some duplicates in one file, does
that count for the problem?

柏江山 ***@***.***> 于2021年4月9日周五 下午9:52写道：

**Comment by LeilyR** [comment] 2021-04-09 15:06
They might be secondary alignments, they should be taken care of. Could you please try to use hicexplorer version 3.4, just that we get sure no bug has been introduced since then. If you still have the issue we will then work on a quick bug fix.

**Comment by jiangshan529** [comment] 2021-04-10 02:11
hi, when I use hicexplorer3.4.3, and use the command: hicBuildMatrix
--samFiles A1_sorted.bam A2_sorted.bam --restrictionCutFile
rest_site_positions.bed --danglingSequence GATC -o chr17_1mb.cool --region
chr17:0-80000000 --binSize 1000000 --restrictionSequence GATC --QCfolder
QC_20_5kb.
it reports this error: hicBuildMatrix: error: argument --binSize/-bs: not
allowed with argument --restrictionCutFile/-rs.

LeilyR ***@***.***> 于2021年4月9日周五 下午11:06写道：

**Comment by LeilyR** [comment] 2021-04-10 04:57
Hi, yes you are right. Up to that version one could only provide one of them. Since you are interested in 1Mb matrices you can drop -rs.

**Comment by jiangshan529** [comment] 2021-04-10 06:53
Well, this time it reports the same error: AssertionError: FATAL ERROR
A00877:597:HVV2LDSXY:2:1101:1217:21887
A00877:597:HVV2LDSXY:2:1101:1217:22326 Be sure that the sam files have the
same read order If using Bowtie2 or Hisat2 add the --reorder option.

LeilyR ***@***.***> 于2021年4月10日周六 下午12:57写道：

**Comment by jiangshan529** [comment] 2021-04-13 01:38
Hi, Good morning. I want to know if you are fixing the bugs or there are
other solutions.
Thanks!

柏江山 ***@***.***> 于2021年4月10日周六 下午2:53写道：

**Comment by LeilyR** [comment] 2021-04-13 07:58
Now I am quite convinced that the issue is the content of your bam files. I could not reproduce this error on a set of fastq files I had here using `bwa = 0.7.17`. What you could do first is trying to update your bwa to the latest version and map your reads again. We have a wrapper around hicexplorer do you want to try that to see if it helps? you can find more about it [here](https://snakepipes.readthedocs.io/en/latest/) Also maybe you can share with me your input, if you want, then I can try to reproduce the bam files and build the matrix to see if i can re-genearate the error.

**Comment by jiangshan529** [comment] 2021-04-13 11:52
Yes, I also use other data and I can build matrix. Can you share me your
personal email and I can send my input to you?

LeilyR ***@***.***> 于 2021年4月13日周二 15:58写道：

**Comment by joachimwolff** [comment] 2021-04-13 12:40
Hi, 

just send me a mail to my address as it is listed in our labs webpage: http://www.bioinf.uni-freiburg.de/team.html?de

I will forward the data to Leily.

Best,

Joachim

**Comment by LeilyR** [comment] 2021-04-29 12:06
as far as i knew this issue has been taken care of over an email exchange. I close it for now , but feel free to reopen if there is still anything left.

**Closed by LeilyR** 2021-04-29 12:06 UTC
