### ISSUE TITLE
Runtime questions

### ISSUE THREAD

**Issue by gabedolpten** [deeptools/HiCExplorer#670] opened 2021-02-08 17:54 UTC
In the "Loop Detection using..." paper, it says that HiCExplorer runs in ~3 minutes. However, when I call hicDetectLoops it takes ~2 hours to run. What is the source of this discrepancy? Am I using it incorrectly?

**Comment by joachimwolff** [comment] 2021-02-08 18:11
Hi,

first of all, please consider the mentioned paper is just a pre-print and is not peer-reviewed. Second, the results in the paper reflect the implementation we had for HiCExplorer version < 3.5. With version 3.5 we introduced many changes to the algorithm to increase its precision, however, we have not updated the pre-print paper so far.

What the causes could be: In the paper, we mention the hardware, it was a computer with 2x XEON E5-2630 v4 @ 2.20GHz i.e. we had 20 cores and 40 parallel threads available and we computed the result using 16 * 12 = 192 threads in parallel. If you don't have this massive parallel computing power and the requested main memory, the execution time will be longer. Second, we also defined that we use a maximal genomic distance of 2 million bases, if you have selected a different (larger) value, it will take longer. Third, the result was computed using interaction matrices in the cooler file format. If you use the native HiCExplorer format `h5`, the execution time will be significantly slower because of the better parallel loading support of `cooler`.

Best,

Joachim

**Comment by joachimwolff** [comment] 2021-02-12 20:18
Reading now this issue: https://github.com/deeptools/HiCExplorer/issues/676.
The paper states it uses 10 kb matrices and not 800 bp if your 2h runtimes question comes from using this matrix.

**Comment by joachimwolff** [comment] 2021-03-01 07:36
No user response. Closing.

**Closed by joachimwolff** 2021-03-01 07:36 UTC
