### ISSUE TITLE
TypeError in utilities::genomicRegion()

### ISSUE THREAD

**Issue by Rungetf** [deeptools/HiCExplorer#252] opened 2018-05-18 08:51 UTC
TypeError raised during testing of `test_trivial_runs.py::test_build_matrix()` due to region parameter:
https://github.com/Rungetf/HiCExplorer/blob/testing/hicexplorer/test/test_trivial_runs.py#L96

@joachimwolff Please check function `utilities::genomicRegion()` and test `test_trivial_runs.py::test_build_matrix()` for this Error.

**Comment by Rungetf** [comment] 2018-05-18 09:16
Seems to work at python 2.7... travis test failed because expected exception wasn`t raised during test.

**Comment by joachimwolff** [comment] 2018-05-18 09:27
@Rungetf Can you merge upstream/master to your branch? I fixed the region argument yesterday, would be good to know if the test case is succeeding now.

**Comment by Rungetf** [comment] 2018-05-18 09:42
@joachimwolff I`ll try. I also got two other exceptions during travis test for test_pca_bedgraph and test_pca_bigwig (both assertionErrors) at python 2.7... I did not write in this testfile so I'll have to check what is wrong there too. Perhaps merging with master will help with this issue too?!

**Comment by joachimwolff** [comment] 2018-05-18 10:04
@Rungetf PCA issues are known and not critical. It is caused by a flip of the sign of some eigenvectors, this happens if not the same (identical) implementation is used.

**Comment by Rungetf** [comment] 2018-05-18 10:52
@joachimwolff ok, but how will I make the test run through at travis if PCA is failing? Or should I include some try except routine for that case?

**Comment by joachimwolff** [comment] 2018-05-18 12:06
Let it fail, I will provide a fix for this issue soon.

**Closed** 2018-10-30 15:29 UTC
