### ISSUE TITLE
Coolers broken

### ISSUE THREAD

**Issue by Phlya** [deeptools/HiCExplorer#216] opened 2018-03-13 12:16 UTC
Discovered when trying to use pyGenomeTracks:
```
Traceback (most recent call last):
  File "/usr/local/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/plotTracks.py", line 278, in main
    track_label_width=args.trackLabelFraction)
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/tracksClass.py", line 119, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/tracksClass.py", line 1726, in __init__
    self.hic_ma = HiCMatrix.hiCMatrix(self.properties['file'], cooler_only_init=True)
  File "/usr/local/lib/python3.5/dist-packages/hicexplorer/HiCMatrix.py", line 122, in __init__
    self.load_cool_only_init(matrixFile)
AttributeError: 'hiCMatrix' object has no attribute 'load_cool_only_init'
```

There is currently no `load_cool_only_init` method, so this fails...

**Comment by joachimwolff** [comment] 2018-03-13 13:17
I have to apologize. I removed this function in the latest version of HiCExplorer because I thought it was dead code. I haven’t had it in mind that Fidel and I actually discussed the usage of this function for pyGenomeTracks. I will bring it back soon as possible.

In the meantime I recommend to use hicExport from HiCExplorer to transfer the cooler matrix to the HiCExplorer h5 file format.

**Comment by joachimwolff** [comment] 2018-04-09 20:15
@phlya Can you check if it is fixed with version 2.1.1? Thanks in advance,

Joachim

**Comment by Phlya** [comment] 2018-04-10 17:01
Hi, thanks for the fix! I now get a different error in PyGenomeTracks, so don't know what to tell you :) Should I report it as an issue there?..

```
s1529682:~/Documents/PhD/Hi-C/pygenometracks$ pyGenomeTracks --tracks Rob_PcG.config --region chr5:28300000-30500000 --outFileName Shh_test.pdf
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

title not set for 'section 1. [hic matrix]'
DEBUG:pygenometracks.tracksClass:self.properties
Traceback (most recent call last):
  File "/usr/local/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/plotTracks.py", line 278, in main
    track_label_width=args.trackLabelFraction)
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/tracksClass.py", line 119, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/tracksClass.py", line 1730, in __init__
    if len(self.hic_ma.matrix.data) == 0:
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by Phlya** [comment] 2018-04-10 17:15
And if I try to plot using hicPlotTADs, I get this error:
```
s1529682:~/Documents/PhD/Hi-C/pygenometracks$ hicPlotTADs --tracks ./Rob_PcG.config --region chr5:28300000-30500000 -o Shh_test.pdf
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:hicexplorer.trackPlot:
title not set for 'section 1. [hic matrix]'

INFO:hicexplorer.HiCMatrix:Number of poor regions to remove: 393 {'chr5': 393}
INFO:hicexplorer.HiCMatrix:found existing 393 nan bins that will be included for masking 
INFO:hicexplorer.trackPlot:1.1071934700012207
Traceback (most recent call last):
  File "/usr/local/bin/hicPlotTADs", line 7, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/hicexplorer/hicPlotTADs.py", line 379, in main
    trp.plot(args.outFileName, *region, title=args.title)
  File "/usr/local/lib/python3.5/dist-packages/hicexplorer/trackPlot.py", line 227, in plot
    track.plot(axis, label_axis, chrom, start, end)
  File "/usr/local/lib/python3.5/dist-packages/hicexplorer/trackPlot.py", line 1010, in plot
    matrix[mask] = matrix[mask is False].min()
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by joachimwolff** [comment] 2018-04-11 14:38
Next week I am back in office and will take care of it. Looks like the data of the matrix is not loaded and therefore it fails.

**Comment by joachimwolff** [comment] 2018-10-18 17:12
@Phlya We have updated the way pyGenomeTracks interacts with Hi-C data. Could you test if the current master version fixes this bug? Thanks a lot!

**Comment by Phlya** [comment] 2018-10-19 14:48
Well, I updated pyGenomeGracks from pypi and install HiCMatrix from GitHub, and here is what I get:
```
s1529682:~/Documents/PhD/Hi-C/pygenometracks$ pyGenomeTracks --tracks Rob_PcG.config --region chr5:28300000-30500000 --outFileName Shh_test.pdf
INFO:hicmatrix.HiCMatrix:Number of poor regions to remove: 2 {'chr5': 2}
INFO:hicmatrix.HiCMatrix:found existing 2 nan bins that will be included for masking 
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:1.0255520343780518
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 11.12. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [hic matrix]
Traceback (most recent call last):
  File "/usr/local/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/plotTracks.py", line 304, in main
    trp.plot(args.outFileName, *region, title=args.title)
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/tracksClass.py", line 246, in plot
    track.plot(plot_axis, chrom, start, end)
  File "/usr/local/lib/python3.5/dist-packages/pygenometracks/tracks/HiCMatrixTrack.py", line 204, in plot
    matrix[mask] = matrix[mask is False].min()
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

Am I doing something wrong?

**Comment by joachimwolff** [comment] 2018-10-19 16:37
Quite old source code is crashing there... The error message means that the matrix is not having any values, i.e. the selected region is only having `0` and no non-zero values. 
Questions that raises is, is this by chance true and you selected a region with only zeros? Or, more likely, what kind of bug is creating an empty matrix? 

Can you check if a) the region contains non-zeros and b) can you transform the cool matrix to a h5 and try to plot it again? (If you don't know how, you can share the matrix with me if you like and I will debug it).

Thanks a lot!

**Comment by Phlya** [comment] 2018-10-22 10:25
a) `cooler show -b` on the file with the same coordinates gives this:
![image](https://user-images.githubusercontent.com/2895034/47288218-128d0f80-d5ed-11e8-936c-1be014fd5870.png)

**Comment by Phlya** [comment] 2018-10-22 10:32
I'm trying to convert to h5, but it's not working:
```
hicExport --inFile /home/s1529682/Datastore/wendy-lab/ilia/data/Hi-C/dist/KM/coolers/library_group/serum-KM.10000.cool -o serum-KM.10000.h5 --outputFormat h5
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "/usr/local/bin/hicExport", line 7, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/hicexplorer/hicExport.py", line 206, in main
    hic_ma = hm.hiCMatrix(matrixFile=args.inFile[0], file_format=args.inputFormat)
  File "/usr/local/lib/python3.5/dist-packages/hicexplorer/HiCMatrix.py", line 84, in __init__
    hiCMatrix.load_h5(matrixFile)
  File "/usr/local/lib/python3.5/dist-packages/hicexplorer/HiCMatrix.py", line 236, in load_h5
    parts[matrix_part] = getattr(f.root.matrix, matrix_part).read()
  File "/usr/local/lib/python3.5/dist-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/usr/local/lib/python3.5/dist-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/usr/local/lib/python3.5/dist-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``matrix``
```

**Comment by joachimwolff** [comment] 2018-10-22 13:32
You need to add '--inputFormat cool' to you command.

**Comment by Phlya** [comment] 2018-10-22 16:47
OK, this command completely froze my computer, does it create dense matrices in memory?

I repeated this with a lower resolution cooler - didn't work with the cooler again. I converted to h5, and it still didn't work with the same error. And again, this is what it look like with `cooler show`:
![image](https://user-images.githubusercontent.com/2895034/47305777-74b43780-d622-11e8-9a57-6ae034175acf.png)

**Comment by joachimwolff** [comment] 2018-10-24 16:39
I confirm this bug, it appears only for `log` `-log` option. Until I have fixed this, you can use `log1p` which is quite similar.

This bug appears because we only tested for `log1p` and never for the other options.

**Comment by joachimwolff** [comment] 2018-10-24 16:57
Bug fix: https://github.com/deeptools/pyGenomeTracks/pull/46

**Comment by Phlya** [comment] 2018-10-25 15:13
Ummm yeah, `log1p` works, but the result is very strange... Looks like it's maybe adding 1 to empty pixels, but then they actually become the highest values by far, because after balancing in coolers the whole column/row sums up to 1? Colorbar only start with 1 though, so not sure what's going on there.
![image](https://user-images.githubusercontent.com/2895034/47510656-796e2b00-d870-11e8-903b-6a2f5a19aaf9.png)


Also, I tried running it with an h5 files at 100kb resolution and it again almost froze my computer to death - is it loading the whole chromosome in a dense format into memory?

**Comment by joachimwolff** [comment] 2018-10-25 19:20
You are correct, the `1p` in `log1p` means add one to the values. Usually this is fine, we deal with values from zero to a few thousands and a 1 more prevents errors caused by 0 in the log function. I hadn't had it in mind that cooler uses a normalisation that arranges all values in a `0 - 1` range.  In my opinion this is problematic because of all the floating point imprecision and slower computations, but maybe that's just a computer scientist view point. Moreover, by a normalization to this range you lose information, it is indeed important to know the number of measured interactions for a bin and not just a relative value of it. I don't understand why this approach is used by cooler. Maybe this is something @gtrichard could ask in the upcoming collaboration. 
To warn you: `log` is mathematically not defined for zero, therefore we set all values for the `log` parameter to the smallest non-zero value. 
My recommendation here is to take the uncorrected values and apply our correction with `hicCorrectMatrix`.
For your data as it is you could try it without log1p or log, or try the patched version of pyGenomeTracks in the bugfix_hic branch.

Concerning the high memory usage:
To my surprise it cost more memory if I get the data in sparse numpy coo format via cooler api and then add `tocsr()` (current stable implementation) compared to getting the values as sparse but as a pandas data frame and transfer it to a numpy csr matrix (how it will be in the next release).  However, in both cases you need a lot of memory, current version needs for e.g. a 10kb cooler containing ~2.1 billion entries so much memory that I cannot load it on my 64 GB machine anymore. With the new implementation it is possible to do that with less than 32 GB. Hi-C computation needs always a lot of memory if you ever need resources I can recommend our webserver: `hicexplorer.usegalaxy.eu`. I think we can give you there up to 200 GB of memory if really needed. Anyhow, it should not be difficult to transfer a 100kb matrix, I think maybe 16 GB should be enough.

**Closed** 2018-10-30 15:37 UTC
