### ISSUE TITLE
 Error in hictransform module

### ISSUE THREAD

**Issue by RicardoGaGu** [deeptools/HiCExplorer#292] opened 2018-10-06 21:56 UTC
Hi!, I'm trying to obtain the observed over expected matrix of all chromosomes stored in this cool file.
I get a strange error when I execute this command:

hicTransform --matrix jurkat_wild_type.cool --outFileName OE_jurkat_wild_type_prova.cool

This is the error:

`INFO:cooler:Creating cooler at "jurkat_wild_type_prova.cool::/"
INFO:cooler:Writing chroms
INFO:cooler:Writing bins
INFO:cooler:Writing pixels
Traceback (most recent call last):
  File "/home/usuaris/spcom/ricardo.garcia.gutierrez/anaconda2/bin/hicTransform", line 7, in <module>
    main()
  File "/home/usuaris/spcom/ricardo.garcia.gutierrez/anaconda2/lib/python2.7/site-packages/hicexplorer/hicTransform.py", line 166, in main
    hic_ma.save(args.outFileName, pSymmetric=False, pApplyCorrection=False)
  File "/home/usuaris/spcom/ricardo.garcia.gutierrez/anaconda2/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1495, in save
    self.save_cooler(pMatrixName, pSymmetric=pSymmetric, pApplyCorrection=pApplyCorrection)
  File "/home/usuaris/spcom/ricardo.garcia.gutierrez/anaconda2/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1367, in save_cooler
    append=False)
  File "/home/usuaris/spcom/ricardo.garcia.gutierrez/anaconda2/lib/python2.7/site-packages/cooler/io.py", line 286, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/home/usuaris/spcom/ricardo.garcia.gutierrez/anaconda2/lib/python2.7/site-packages/cooler/_writer.py", line 203, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/home/usuaris/spcom/ricardo.garcia.gutierrez/anaconda2/lib/python2.7/site-packages/cooler/_binning.py", line 1358, in _validate_pixels
    raise BadInputError("Found bin1_id greater than bin2_id")
cooler._binning.BadInputError: Found bin1_id greater than bin2_id`

Anyone know what's going on?

**Comment by joachimwolff** [comment] 2018-10-07 10:09
Hi,

which version of HiCExplorer and cooler do you use? I have seen this error in the past once, the reason here was was a stricter input validation of a new cooler version (I think it was from version 0.7.6 to 0.7.9) and therefore matrices with values which are not in the upper triangle are raising this error. See https://github.com/mirnylab/cooler/issues/116
I tried to fix this error but had the issue that I could not reproduce this error. It would be nice if you can provide me your matrix, maybe I can finally reproduce and fix this issue.

Best,

Joachim

**Comment by RicardoGaGu** [comment] 2018-10-08 21:50
Cooler version: 0.7.11
Hicexplorer version :  2.1.1

I can send you the link privately.

Thanks a lot,
Ricardo

**Comment by joachimwolff** [comment] 2018-10-30 15:21
No feedback so far. Closing.

**Closed by joachimwolff** 2018-10-30 15:21 UTC
