### ISSUE TITLE
processing non-contact matrices returns an error

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#304] opened 2018-10-31 09:46 UTC
I keep getting this error when I am trying to process a matrix which is not a contact matrix like pearson or obs_exp_liebermann. I suspect if has something to do with hicMatrix. I am using v3 from Conda, so I wonder if it is master and should use develop?

DEBUG:hicexplorer.hicExport:None
Traceback (most recent call last):
  File "/home/rabbani/miniconda3/bin/hicExport", line 7, in <module>
    main()
  File "/home/rabbani/miniconda3/lib/python3.6/site-packages/hicexplorer/hicExport.py", line 206, in main
    hic_ma = hm.hiCMatrix(matrixFile=args.inFile[0], file_format=args.inputFormat)
  File "/home/rabbani/miniconda3/lib/python3.6/site-packages/hicexplorer/HiCMatrix.py", line 84, in __init__
    hiCMatrix.load_h5(matrixFile)
  File "/home/rabbani/miniconda3/lib/python3.6/site-packages/hicexplorer/HiCMatrix.py", line 272, in load_h5
    distance_counts = f.root.correction_factors.read()
  File "/home/rabbani/miniconda3/lib/python3.6/site-packages/tables/group.py", line 840, in __getattr__
    return self._f_get_child(name)
  File "/home/rabbani/miniconda3/lib/python3.6/site-packages/tables/group.py", line 712, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/rabbani/miniconda3/lib/python3.6/site-packages/tables/group.py", line 399, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``correction_factors``

**Comment by joachimwolff** [comment] 2018-10-31 10:07
Hi Leily,

is it the development version of HiCExplorer or the master from conda?

Best,

Joachim

**Comment by joachimwolff** [comment] 2018-10-31 10:19
I know this error message and I fixed this some time ago. This fix is part of version 3 of HiCMatrix, anyhow, you should no longer use hicExport, it is no longer part of the development version of HiCExplorer and is replaced by hicConvertFormat and hicAdjustMatrix.
I am a bit confused right now, I think you have maybe a mix of different development stages? Difficult to tell from the distance.

**Comment by LeilyR** [comment] 2018-10-31 10:35
Hi Joachim,
They both trow this error. However, they both work fine on contact matrices. Some issue in writing non-contact matrices .h5 file maybe? want me to send you a matrix? drop me an email if you need one.

**Comment by LeilyR** [comment] 2018-10-31 10:47
One more peace of info. which might help you figuring the issue out is that it works if --chromosome has been mentioned and one chr has been set to it.

**Comment by joachimwolff** [comment] 2018-10-31 10:56
Which tool do you use? hicConvertFormat or hicAdjustMatrix?

**Comment by LeilyR** [comment] 2018-10-31 11:01
Today, I have tried  hicExport. I did try another module which reads the matrix some time ago and the error was the same. The one I cannot remember though maybe  hicPlotTADs

**Comment by joachimwolff** [comment] 2018-10-31 11:12
I think we talk here about different things:
- hicExport is existing only in the master branch and in the conda version including version 2.1.4 of HiCExplorer. In this setting, the bug you describe is present and I confirm the existence.
- In the development branch `hicExport` is no longer existing i.e. you should not be able to call it. If you can, please clean your environment or create a fresh one. Please check via `whereis` and `which` that the correct version is used, it should be the one in your environment and not in the root environment of conda. The bug you describe is fixed with version 3 of HiCMatrix and I am not able to reproduce it with the current hicConvertMatrix and hicAdjustMatrix and at least version 3 of HiCMatrix. Please use for hicAdjustMatrix the current development branch of HiCMatrix, if you don't the masking will not work.

**Comment by LeilyR** [comment] 2018-10-31 11:24
~/Tools/hicexplorer/HiCExplorer$ hicExport --version
/home/rabbani/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
DEBUG:hicexplorer.hicExport:None
hicExport 2.2-dev

**Comment by joachimwolff** [comment] 2019-02-04 18:06
I guess this can be closed because there is no more hicExport.

**Closed by joachimwolff** 2019-02-04 18:06 UTC
