### ISSUE TITLE
HiCExplorer v2.0 installation error

### ISSUE THREAD

**Issue by CMylonas** [deeptools/HiCExplorer#179] opened 2018-01-23 17:25 UTC
Installed v2.0 via
pip install git+https://github.com/deeptools/HiCExplorer@2.0.1-bugfix

I get the following error every time I run any of the commands. The 1.8v seems to be running smoothly.

Traceback (most recent call last):
  File "/beegfs/group_pt/home/CMylonas/.Python/2.7/bin/hicFindTADs", line 4, in <module>
    from hicexplorer.hicFindTADs import main
  File "/beegfs/group_pt/home/CMylonas/.Python/2.7/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 9, in <module>
    from hicexplorer import HiCMatrix as hm
  File "/beegfs/group_pt/home/CMylonas/.Python/2.7/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 20, in <module>
    import cooler
  File "/beegfs/group_pt/home/CMylonas/.Python/2.7/lib/python2.7/site-packages/cooler/__init__.py", line 32, in <module>
    from .api import Cooler, get, info, chroms, bins, pixels, matrix, annotate
  File "/beegfs/group_pt/home/CMylonas/.Python/2.7/lib/python2.7/site-packages/cooler/api.py", line 10, in <module>
    import h5py
  File "build/bdist.linux-x86_64/egg/h5py/__init__.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/h5py/_errors.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/h5py/_errors.py", line 6, in __bootstrap__
ImportError: libhdf5.so.9: cannot open shared object file: No such file or directory

**Comment by bgruening** [comment] 2018-01-23 17:33
Can you check if you have libhdf5 installed on your system?
If not could you use conda as packages manager and try a `conda create -n hicexplorer hicexplorer -c bioconda`?

**Comment by joachimwolff** [comment] 2018-01-24 09:36
Thanks a lot for using HiCExplorer. 
I saw that you are new on github, therefore I want to clarify that the recommended stable version is always the in master branch. This release is available per conda as @bgruening already mentioned and is the recommended way to install the HiCExplorer. In non-master branches we develop new features or as it is with the 2.0.1-bugfix branch, collect bug fixes for a next release. This means that the 2.0.1-bugfix branch is not declared as stable and should only be used if you know what you do. 
Anyway, I appreciate it that someone is testing the bugfix branch, this helps a lot to detect errors in an early stage. It looks like you are missing dependencies. The dependencies are listed in the `requirements.txt` file, for Python 2.7 you need to add the dependency `configparser`.
To fix you issue: 
`pip install -r requirements.txt && pip install configparser`
The requirements.txt file you can find here: https://github.com/deeptools/HiCExplorer/blob/master/requirements.txt

**Comment by fidelram** [comment] 2018-01-24 10:00
I suggested @CMylonas to put the issue here as they are interested on running `hicPCA` which is not yet part of the master branch.

**Comment by joachimwolff** [comment] 2018-01-24 10:30
@fidelram `hicPCA` is part of the 2.0 release. Or do you mean specific bug fixes in 2.0.1?

**Comment by fidelram** [comment] 2018-01-24 13:24
The original message I got before moving to github was:

```
... hicPCA is only available in v2.0 which is not available through "pip".
I downloaded it directly from github but I'm getting the following error:

File "build/bdist.linux-x86_64/egg/h5py/__init__.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/h5py/_errors.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/h5py/_errors.py", line 6, in __bootstrap__
ImportError: libhdf5.so.9: cannot open shared object file: No such file or directory
```

Thus I suggested the bugfix branch. But the problem seems to be cooler and hdf5 version in either case. 

One option is to start a new environment with conda and install a fresh copy of cooler.

**Comment by fidelram** [comment] 2018-01-24 14:03
@CMylonas How did you installed cooler? 

If you install it using conda (or the conda version of HiCExplorer) this may help: I had a similar hdf5 issue. I found which version of hdf5 was used for the conda package I needed and then installed that hdf5 version.

**Comment by CMylonas** [comment] 2018-01-24 15:31
@fidelram 
I had a problem installing some dependencies with conda.
The core facility installed v2.0 for me through conda and now it works fine

Thank you for all the suggestions

**Comment by joachimwolff** [comment] 2018-01-24 15:52
@CMylonas Good to hear that it works now. 
@fidelram Does this mean we have to manage the dependencies with pip better? I just try to understand what went wrong and how we can improve based on this.

**Comment by fidelram** [comment] 2018-01-24 18:02
I don't know if this is related with pip or with conda or both. @CMylonas, in case we have a similar issue in the future, can you tell us how did you first installed HiCExplorer? To update you used pip and that is when you got the error right?

**Comment by CMylonas** [comment] 2018-01-24 19:23
@fidelram 
Exactly!
pip install caused the error  whereas with conda it runs smoothly

**Comment by joachimwolff** [comment] 2018-01-25 16:12
I tried to reproduce it in a new conda environment and failed. I was using the command `pip install git+https://github.com/deeptools/HiCExplorer@2.0.1-bugfix`. If I run any command e.g. `hicBuildMatrix --help` it runs without an error.

**Closed** 2018-01-30 08:51 UTC
